"""empty message

Revision ID: 21345bfa4299
Revises: e49714b086b3
Create Date: 2023-03-18 15:38:01.460769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21345bfa4299'
down_revision = 'e49714b086b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_items',
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('order_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_items')
    # ### end Alembic commands ###
