"""empty message

Revision ID: d4cba5317710
Revises: e053e30ba104
Create Date: 2023-04-16 13:21:27.447422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cba5317710'
down_revision = 'e053e30ba104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_propId_user_id', ['propId', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint('unique_propId_user_id', type_='unique')

    # ### end Alembic commands ###
