"""empty message

Revision ID: e49714b086b3
Revises: 
Create Date: 2023-03-16 09:40:50.313171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49714b086b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('propId', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('zcode', sa.Integer(), nullable=True),
    sa.Column('county', sa.String(length=25), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('yearBuilt', sa.Integer(), nullable=True),
    sa.Column('numBeds', sa.Integer(), nullable=True),
    sa.Column('numBaths', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('propId')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_zcode'), ['zcode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_zcode'))
        batch_op.drop_index(batch_op.f('ix_property_county'))
        batch_op.drop_index(batch_op.f('ix_property_city'))

    op.drop_table('property')
    # ### end Alembic commands ###
